pipeline {
  agent {
    docker { image 'pdhunganaa/myy-jenkins-with-git:latest' } 
  }
  stages {
    stage('Test') {
      steps {
        script {
          sh 'node --version'
        }
      }
    }
  }
}
